[ClassVersion("1.0.0.0"), FriendlyName("xAzureBlobFiles")]
class MSFT_xAzureBlobFiles : OMI_BaseResource
{
    [Key] String Path;
    [Required] String StorageAccountName;
    [Required] String StorageAccountKey;
    [Required] String StorageAccountContainer;    
};
